# Generated by Django 5.2.16 on 2026-08-11 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0004_attribution_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegosWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(editable=False, max_length=128, unique=True),
                ),
                ("event_type", models.CharField(editable=False, max_length=64)),
                (
                    "item_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("payload", models.JSONField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("retry", "Retry"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("next_attempt_at", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="regos_webhook_due_idx",
                    )
                ],
            },
        ),
    ]
