# Generated by Django 5.2.17 on 2026-08-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_options_alter_courseaccess_options_and_more"),
        ("payments", "0001_initial"),
        ("store", "0043_alter_basket_created_at_alter_basket_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платёж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterModelOptions(
            name="paymentevent",
            options={
                "verbose_name": "Событие платежа",
                "verbose_name_plural": "События платежей",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.PositiveBigIntegerField(verbose_name="Сумма"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="courses.coursepurchase",
                verbose_name="Покупка курса",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="UZS", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="idempotency_digest",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ключ защиты от дублирования",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Служебные данные"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="store.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                db_index=True,
                default="manual",
                max_length=40,
                verbose_name="Платёжная система",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID платежа в платёжной системе",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Успешен"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменён"),
                    ("refunded", "Возвращён"),
                ],
                db_index=True,
                default="created",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата получения"
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="event_type",
            field=models.CharField(max_length=100, verbose_name="Тип события"),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="external_event_id",
            field=models.CharField(
                max_length=255, verbose_name="ID события в платёжной системе"
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="payload_hash",
            field=models.CharField(
                max_length=64, verbose_name="Хеш содержимого события"
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="payments.payment",
                verbose_name="Платёж",
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="processing_status",
            field=models.CharField(
                choices=[("received", "Получено"), ("processed", "Обработано")],
                default="received",
                max_length=20,
                verbose_name="Статус обработки",
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="provider",
            field=models.CharField(max_length=40, verbose_name="Платёжная система"),
        ),
    ]
