# Generated by Django 5.0.2 on 2024-05-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_used',
            field=models.BooleanField(default=False),
        ),
    ]
