# Generated by Django 5.2.16 on 2026-08-21 01:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auth_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationchallenge',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='phoneverificationchallenge',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='phoneverificationchallenge',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('kind', models.CharField(choices=[
                    ('password_reset', 'Password reset'),
                    ('email_verification', 'Email verification'),
                    ('phone_change', 'Phone change'),
                ], max_length=32)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=16)),
                ('identifier', models.CharField(max_length=254)),
                ('code_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[
                    ('pending', 'Pending'),
                    ('sent', 'Sent'),
                    ('unknown', 'Delivery unknown'),
                    ('failed', 'Delivery failed'),
                    ('consumed', 'Consumed'),
                    ('locked', 'Locked'),
                ], default='pending', max_length=12)),
                ('attempts_remaining', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('resend_after', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='auth_challenges',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'indexes': [
                    models.Index(fields=['kind', 'identifier'], name='users_auth_ch_kind_id_idx'),
                    models.Index(fields=['expires_at'], name='users_auth_ch_exp_idx'),
                ],
            },
        ),
    ]
