# Generated by Django 5.2.17 on 2026-08-26 09:01

import users.validators.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_phoneverificationchallenge_delivery_channel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="bonus_used",
            field=models.BooleanField(
                default=False, verbose_name="Бонус уже использован"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления аккаунта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Почта подтверждена"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[users.validators.phone.validate_phone],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Телефон подтверждён"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Имя пользователя"
            ),
        ),
    ]
