# Generated by Django 5.2.17 on 2026-10-05 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_options_alter_user_bonus_used_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavdoqShopperSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("uz", "Oʻzbekcha")], max_length=2
                    ),
                ),
                ("credential_digest", models.CharField(max_length=64)),
                ("access_token", models.TextField()),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия AI-чата",
                "verbose_name_plural": "Сессии AI-чата",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="users_savdoq_session_exp_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "language"),
                        name="users_savdoq_session_user_language_unique",
                    )
                ],
            },
        ),
    ]
