# Generated by Django 5.0.2 on 2024-03-14 18:59

import ckeditor.fields
import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Общая сумма')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Кол-во товара')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_uz', models.CharField(max_length=255, unique=True, verbose_name='Название блога uz')),
                ('name_ru', models.CharField(max_length=255, unique=True, verbose_name='Название блога ru')),
                ('photo', models.ImageField(upload_to=store.models.blog_directory_path, verbose_name='Картинка блога')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='Описание блога uz')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Описание блога ru')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бренда')),
                ('photo', models.ImageField(upload_to=store.models.brand_directory_path, verbose_name='Фотография бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название категории uz')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название категории ru')),
                ('photo', models.ImageField(upload_to=store.models.category_directory_path, verbose_name='Картинка категории')),
                ('sort', models.PositiveIntegerField(blank=True, help_text='сортируется по возрастанию, у каждой категории должен быть уникальный номер', null=True, verbose_name='Сортировка Категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название филиала uz')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название филиала ru')),
                ('address_uz', models.CharField(help_text='Адрес филиала, а не ссылка (Рес. Узбекистан, г. Бухара, ул. Абдулла кодирий 100 дом)', max_length=255, verbose_name='Адрес филиала (без ссылки) uz')),
                ('address_ru', models.CharField(help_text='Адрес филиала, а не ссылка (Рес. Узбекистан, г. Бухара, ул. Абдулла кодирий 100 дом)', max_length=255, verbose_name='Адрес филиала (без ссылки) ru')),
                ('work_time_start', models.TimeField(help_text='от ПН. до СБ.', verbose_name='Время старта работы')),
                ('work_time_end', models.TimeField(help_text='от ПН. до СБ.', verbose_name='Время заканчиваие работы')),
                ('day_off', models.CharField(help_text='Если вы работаете в выходные дни, то пишите время с какого часа до какого вы работаете, если нет то пишилте Выходной', max_length=255, verbose_name='Выходной')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон номер филиала')),
                ('address_url', models.URLField(verbose_name='Адрес филиала (только ссылка)')),
                ('photo', models.ImageField(upload_to='filial/', verbose_name='Фотография филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Дайте название для этого меню')),
                ('about_uz', ckeditor.fields.RichTextField(help_text='Текст для раздела о нас uz', verbose_name='О нас')),
                ('about_ru', ckeditor.fields.RichTextField(help_text='Текст для раздела о нас ru', verbose_name='О нас')),
                ('blog_uz', ckeditor.fields.RichTextField(help_text='Текст для раздела Блог uz', verbose_name='Блог')),
                ('blog_ru', ckeditor.fields.RichTextField(help_text='Текст для раздела Блог ru', verbose_name='Блог')),
                ('set_product_uz', ckeditor.fields.RichTextField(help_text='Текст для раздела Комплект uz', verbose_name='Комплект')),
                ('set_product_ru', ckeditor.fields.RichTextField(help_text='Текст для раздела Комплект ru', verbose_name='Комплект')),
                ('delivery_and_payment_uz', ckeditor.fields.RichTextField(help_text='Текст для раздела Доставка и Оплата', verbose_name='Доставка и Оплата uz')),
                ('delivery_and_payment_ru', ckeditor.fields.RichTextField(help_text='Текст для раздела Доставка и Оплата', verbose_name='Доставка и Оплата ru')),
                ('is_active', models.BooleanField(default=True, help_text='Если отключено, то не будет видно', unique=True, verbose_name='Активировать')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.PositiveBigIntegerField(default=0)),
                ('type', models.CharField(choices=[('dcb', 'Доставка по городу Бухара'), ('dtu', 'Доставка по всему Узбекистану'), ('pickup', 'Самовывоз')], max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('status', models.CharField(choices=[('purchased', 'Куплен'), ('moderation', 'На модерации')], default='moderation', max_length=50)),
                ('order_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_uz', models.CharField(max_length=100, unique=True, verbose_name='Название Продукта uz')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Название Продукта ru')),
                ('description_uz', ckeditor.fields.RichTextField(verbose_name='Описание Товара uz')),
                ('description_ru', ckeditor.fields.RichTextField(verbose_name='Описание Товара ru')),
                ('price', models.PositiveBigIntegerField(verbose_name='Стоимость товара')),
                ('is_new', models.BooleanField(default=True, help_text='Если вкл. то на сайте будет показывать, что этот товар "Новинка"', verbose_name='Новый товар')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол-во. Товара на складе')),
                ('discounted_price', models.PositiveBigIntegerField(default=0, help_text='Если есть скидка на товар, то вы должны здесь написать на какую сумму скидка (пример: сам товар стоит 120000 сум, скидка на 20000 сум. итог:100000здесь 20000 сум скидочная цена)', verbose_name='Скидочная цена')),
                ('slug', models.SlugField(help_text='без пробела, либо через "-", либо через "_"', max_length=255, unique=True, verbose_name='Название товара (url)')),
                ('country_uz', models.CharField(max_length=100, unique=True, verbose_name='Старана-Производитель uz')),
                ('country_ru', models.CharField(max_length=100, unique=True, verbose_name='Старана-Производитель ru')),
                ('composition_uz', ckeditor.fields.RichTextField(verbose_name='Состав продукта uz')),
                ('composition_ru', ckeditor.fields.RichTextField(verbose_name='Состав продукта ru')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во. просмотров')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=store.models.product_image_directory_path, verbose_name='Фото продукта')),
            ],
            options={
                'verbose_name': 'Картинка продукта',
                'verbose_name_plural': 'Картинки продуктов',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментария')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название комплекта uz')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название комплекта ru')),
                ('photo', models.ImageField(upload_to='set/%Y/%m/%d', verbose_name='Картинка комплекта')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
            },
        ),
    ]
