# Generated by Django 5.0.2 on 2024-03-14 21:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Состав продукта ru'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Состав продукта uz'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_ru',
            field=models.CharField(max_length=100, verbose_name='Старана-Производитель ru'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_uz',
            field=models.CharField(max_length=100, verbose_name='Старана-Производитель uz'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Товара ru'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Товара uz'),
        ),
        migrations.AlterField(
            model_name='product',
            name='set_of_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='products', to='store.setofproduct', verbose_name='Выберите Комплект'),
        ),
    ]
