# Generated by Django 5.0.2 on 2024-02-26 11:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setofproduct',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание блога'),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название блога'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='filial',
            name='day_off_en',
            field=models.CharField(help_text='Если вы работаете в выходные дни, то пишите время с какого часа до какого вы работаете, если нет то пишилте Выходной', max_length=255, null=True, verbose_name='Выходной'),
        ),
        migrations.AddField(
            model_name='filial',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название филиала'),
        ),
        migrations.AddField(
            model_name='menu',
            name='about_en',
            field=ckeditor.fields.RichTextField(help_text='Текст для раздела о нас', null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='menu',
            name='blog_en',
            field=ckeditor.fields.RichTextField(help_text='Текст для раздела Блог', null=True, verbose_name='Блог'),
        ),
        migrations.AddField(
            model_name='menu',
            name='delivery_and_payment_en',
            field=ckeditor.fields.RichTextField(help_text='Текст для раздела Доставка и Оплата', null=True, verbose_name='Доставка и Оплата'),
        ),
        migrations.AddField(
            model_name='menu',
            name='set_product_en',
            field=ckeditor.fields.RichTextField(help_text='Текст для раздела Комплект', null=True, verbose_name='Комплект'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Состав продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Старана-Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание Товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название Продукта'),
        ),
    ]
