# Generated by Django 5.0.2 on 2024-04-06 12:57

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fix_check',
            field=models.FileField(default=1, upload_to=store.models.check_path),
            preserve_default=False,
        ),
    ]
