# Generated by Django 5.0.2 on 2024-03-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_favorite_product_remove_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveBigIntegerField(verbose_name='Кол-во товара'),
        ),
    ]
