# Generated by Django 5.0.2 on 2024-04-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_email_order_fix_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('purchased', 'Куплен'), ('moderation', 'На модерации')], default='На модерации', max_length=50),
        ),
    ]
