# Generated by Django 5.0.2 on 2024-04-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='bank_card_number',
            field=models.CharField(default=30000, help_text='0000 0000 0000 0000', max_length=16, verbose_name='Номер Банковской карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Цена Доставки'),
        ),
    ]
