# Generated by Django 5.0.2 on 2024-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_filial_address_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='address_location',
            field=models.TextField(default=None, verbose_name='Локация филиала (только ссылка)'),
        ),
    ]
