# Generated by Django 5.0.2 on 2024-04-21 23:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_filial_address_location_alter_filial_address_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='без пробела, либо через "-", либо через "_"'),
        ),
        migrations.AddField(
            model_name='menu',
            name='bukhara_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по Бухаре)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='uzbekistan_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по узб.)'),
        ),
        migrations.AddField(
            model_name='setofproduct',
            name='slug',
            field=models.SlugField(null=True, verbose_name='без пробела, либо через "-", либо через "_"'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
