# Generated by Django 5.0.2 on 2024-04-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_description_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True, verbose_name='без пробела, либо через "-", либо через "_"'),
        ),
    ]
