# Generated by Django 5.0.2 on 2024-04-22 00:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='bukhara_description',
            new_name='bukhara_description_ru',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='uzbekistan_description',
            new_name='uzbekistan_description_ru',
        ),
        migrations.AddField(
            model_name='menu',
            name='bukhara_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по Бухаре)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='uzbekistan_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по узб.)'),
        ),
    ]
