# Generated by Django 5.0.2 on 2024-05-03 01:09

import ckeditor.fields
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_bukhara_description_menu_bukhara_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='address_location',
            field=models.TextField(default=None, verbose_name='Локация филиала (только ссылка)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='bukhara_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по Бухаре) ru'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='bukhara_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по Бухаре) uz'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uzbekistan_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по узб.) ru'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uzbekistan_description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание (Доставка по узб.) uz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fix_check',
            field=models.FileField(null=True, upload_to=store.models.check_path),
        ),
    ]
