# Generated by Django 5.0.2 on 2024-05-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
