# Generated by Django 5.0.2 on 2024-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', related_query_name='products', to='store.category', verbose_name='Категория продукта'),
        ),
    ]
