# Generated by Django 5.0.2 on 2024-05-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='bonus',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Бонусная цена'),
        ),
    ]
