# Generated by Django 5.0.2 on 2025-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_menu_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название Продукта ru'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название Продукта uz'),
        ),
    ]
