# Generated by Django 5.0.2 on 2025-04-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
