# Generated by Django 5.0.2 on 2025-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_remove_coupon_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="address_location",
            field=models.TextField(
                blank=True, null=True, verbose_name="Локация филиала (только ссылка)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Название Продукта ru"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Название Продукта uz"
            ),
        ),
    ]
