# Generated by Django 5.0.2 on 2025-06-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_alter_filial_address_location_alter_product_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Название Продукта ru"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Название Продукта uz"
            ),
        ),
    ]
