# Generated by Django 5.0.2 on 2026-02-14 14:52

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_alter_product_name_ru_alter_product_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="address_location",
            field=models.TextField(
                default=None, verbose_name="Локация филиала (только ссылка)"
            ),
        ),
        migrations.CreateModel(
            name="Product360Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=store.models.product_360_directory_path,
                        verbose_name="Фото для 360°",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем раньше показывается кадр",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_360_images",
                        related_query_name="product_360_images",
                        to="store.product",
                        verbose_name="360° изображения продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "360° Изображение продукта",
                "verbose_name_plural": "360° Изображения продуктов",
                "ordering": ["sort_order"],
            },
        ),
    ]
