# Generated by Django 5.0.2 on 2026-02-24 23:33

import django.db.models.deletion
import store.models
from django.db import migrations, models


def copy_old_filial_photo_to_gallery(apps, schema_editor):
    Filial = apps.get_model("store", "Filial")
    FilialPhoto = apps.get_model("store", "FilialPhoto")

    filiales_with_photo = Filial.objects.exclude(photo="").exclude(photo__isnull=True)

    for filial in filiales_with_photo:
        photo_name = str(filial.photo)
        if photo_name and not FilialPhoto.objects.filter(filial_id=filial.id, photo=photo_name).exists():
            FilialPhoto.objects.create(filial_id=filial.id, photo=photo_name)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_alter_filial_address_location_product360image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filial",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="filial/",
                verbose_name="Фотография филиала",
            ),
        ),
        migrations.CreateModel(
            name="FilialPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ImageField(
                        upload_to=store.models.filial_image_directory_path,
                        verbose_name="Фотография филиала",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        related_query_name="photos",
                        to="store.filial",
                        verbose_name="Филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото филиала",
                "verbose_name_plural": "Фото филиалов",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RunPython(copy_old_filial_photo_to_gallery, migrations.RunPython.noop),
    ]
