# Generated by Django 5.2.16 on 2026-08-08 02:16

import store.fields
from django.db import migrations

from store.content.policies.v1 import sanitize_html_v1


HTML_FIELDS = {
    "Blog": ("description_ru", "description_uz"),
    "Category": ("description",),
    "Menu": (
        "about_ru",
        "about_uz",
        "blog_ru",
        "blog_uz",
        "bukhara_description_ru",
        "bukhara_description_uz",
        "delivery_and_payment_ru",
        "delivery_and_payment_uz",
        "set_product_ru",
        "set_product_uz",
        "uzbekistan_description_ru",
        "uzbekistan_description_uz",
    ),
    "Product": (
        "composition_ru",
        "composition_uz",
        "description_ru",
        "description_uz",
    ),
}


def sanitize_existing_html(apps, schema_editor):
    database = schema_editor.connection.alias
    for model_name, field_names in HTML_FIELDS.items():
        model = apps.get_model("store", model_name)
        manager = model.objects.using(database)
        records = manager.only("pk", *field_names)
        changed = []
        for record in records.iterator(chunk_size=200):
            dirty = False
            for field_name in field_names:
                value = getattr(record, field_name)
                sanitized = sanitize_html_v1(value)
                if sanitized != value:
                    setattr(record, field_name, sanitized)
                    dirty = True
            if dirty:
                changed.append(record)
            if len(changed) == 200:
                manager.bulk_update(changed, field_names, batch_size=200)
                changed.clear()
        if changed:
            manager.bulk_update(changed, field_names, batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_order_idempotency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description_ru",
            field=store.fields.SanitizedHtmlField(verbose_name="Описание блога ru"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description_uz",
            field=store.fields.SanitizedHtmlField(verbose_name="Описание блога uz"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=store.fields.SanitizedHtmlField(verbose_name="Описание категории"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="about_ru",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела о нас ru", verbose_name="О нас"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="about_uz",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела о нас uz", verbose_name="О нас"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="blog_ru",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела Блог ru", verbose_name="Блог"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="blog_uz",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела Блог uz", verbose_name="Блог"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="bukhara_description_ru",
            field=store.fields.SanitizedHtmlField(
                null=True, verbose_name="Описание (Доставка по Бухаре) ru"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="bukhara_description_uz",
            field=store.fields.SanitizedHtmlField(
                null=True, verbose_name="Описание (Доставка по Бухаре) uz"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="delivery_and_payment_ru",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела Доставка и Оплата",
                verbose_name="Доставка и Оплата ru",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="delivery_and_payment_uz",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела Доставка и Оплата",
                verbose_name="Доставка и Оплата uz",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="set_product_ru",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела Комплект ru", verbose_name="Комплект"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="set_product_uz",
            field=store.fields.SanitizedHtmlField(
                help_text="Текст для раздела Комплект uz", verbose_name="Комплект"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="uzbekistan_description_ru",
            field=store.fields.SanitizedHtmlField(
                null=True, verbose_name="Описание (Доставка по узб.) ru"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="uzbekistan_description_uz",
            field=store.fields.SanitizedHtmlField(
                null=True, verbose_name="Описание (Доставка по узб.) uz"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition_ru",
            field=store.fields.SanitizedHtmlField(
                blank=True, null=True, verbose_name="Состав продукта ru"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition_uz",
            field=store.fields.SanitizedHtmlField(
                blank=True, null=True, verbose_name="Состав продукта uz"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=store.fields.SanitizedHtmlField(
                blank=True, null=True, verbose_name="Описание Товара ru"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=store.fields.SanitizedHtmlField(
                blank=True, null=True, verbose_name="Описание Товара uz"
            ),
        ),
        migrations.RunPython(sanitize_existing_html, migrations.RunPython.noop),
    ]
