# Generated by Django 5.2.16 on 2026-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0036_sanitize_rich_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                related_query_name="products",
                to="store.category",
                verbose_name="Категория продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="set_of_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                related_query_name="products",
                to="store.setofproduct",
                verbose_name="Выберите Комплект",
            ),
        ),
    ]
