# Generated by Django 5.2.16 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_ineffective_m2m_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regos_item_articul',
            field=models.CharField(blank=True, db_index=True, help_text='Заполняется автоматически при синхронизации с REGOS.', max_length=255, verbose_name='Артикул REGOS'),
        ),
        migrations.AddField(
            model_name='product',
            name='regos_item_code',
            field=models.CharField(blank=True, db_index=True, help_text='Заполняется автоматически при синхронизации с REGOS.', max_length=100, verbose_name='Код номенклатуры REGOS'),
        ),
        migrations.AddField(
            model_name='product',
            name='regos_item_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Заполняется автоматически при синхронизации с REGOS.', null=True, unique=True, verbose_name='REGOS ID номенклатуры'),
        ),
    ]
