# Generated by Django 5.2.16 on 2026-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_product_regos_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="regos_catalog_status",
            field=models.CharField(
                choices=[
                    ("manual", "Обычная карточка"),
                    ("draft", "Черновик из REGOS"),
                    ("published", "Опубликован из REGOS"),
                    ("archived", "Архивирован из REGOS"),
                ],
                db_index=True,
                default="manual",
                help_text="Черновики и архивированные позиции не показываются на витрине и недоступны для заказа.",
                max_length=16,
                verbose_name="Статус карточки REGOS",
            ),
        ),
    ]
