# Generated by Django 5.2.17 on 2026-08-26 09:01

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0042_merge_20260825_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="basket",
            name="order",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="baskets",
                related_query_name="baskets",
                to="store.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="baskets",
                related_query_name="baskets",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="product_name_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Название товара на русском на момент заказа",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="product_name_uz",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Название товара на узбекском на момент заказа",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="product_type",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Тип товара"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="filial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="filialphoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Адрес доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_note",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1000,
                verbose_name="Комментарий покупателя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Стоимость доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Код способа доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_slot_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата доставки"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_slot_label",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Интервал доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_zone_code",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Код зоны доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_price",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Сумма скидки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fix_check",
            field=models.FileField(
                null=True,
                upload_to=store.models.check_path,
                verbose_name="Чек об оплате",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("confirmed", "Подтверждён"),
                    ("preparing", "Готовится"),
                    ("ready", "Готов к выдаче"),
                    ("delivering", "В доставке"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменён"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Статус выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Имя получателя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="idempotency_digest",
            field=models.CharField(
                editable=False,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ключ защиты от дублирования",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Номер заказа"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Не оплачен"),
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Ошибка оплаты"),
                    ("refunded", "Возвращён"),
                ],
                db_index=True,
                default="unpaid",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=13, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="order",
            name="request_fingerprint",
            field=models.CharField(
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Отпечаток запроса",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("purchased", "Куплен"), ("moderation", "На модерации")],
                default="moderation",
                max_length=50,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal_price",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Сумма товаров без скидки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Итоговая сумма"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("dcb", "Доставка по городу Бухара"),
                    ("dtu", "Доставка по всему Узбекистану"),
                    ("pickup", "Самовывоз"),
                ],
                max_length=100,
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="setofproduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
