# Generated by Django 5.2.17 on 2026-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0044_coupon_code_case_insensitive_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="regos_catalog_status",
            field=models.CharField(
                choices=[
                    ("manual", "Обычная карточка"),
                    ("draft", "Черновик из REGOS"),
                    ("published", "Опубликован из REGOS"),
                    ("archived", "Архивирован из REGOS"),
                ],
                db_index=True,
                default="manual",
                help_text="Черновики видны на витрине, но недоступны для заказа. Архивированные позиции скрыты.",
                max_length=16,
                verbose_name="Статус карточки REGOS",
            ),
        ),
    ]
