# Generated by Django 5.0.2 on 2025-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(),
        ),
    ]
