# Generated by Django 5.2.17 on 2026-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleg", "0004_alter_chat_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_id",
            field=models.CharField(max_length=255, verbose_name="ID чата"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="last_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="username",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Имя пользователя Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="secretphrase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="secretphrase",
            name="expired_date",
            field=models.DateTimeField(verbose_name="Действует до"),
        ),
        migrations.AlterField(
            model_name="secretphrase",
            name="phrase",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Секретный ключ"
            ),
        ),
    ]
