# Generated by Django 5.2.17 on 2026-08-26 09:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_telegram", "0002_chat_delivery_limit_and_link_attempt_constraint"),
        ("users", "0008_alter_user_options_alter_user_bonus_used_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customertelegramcampaign",
            options={
                "permissions": (
                    (
                        "test_customertelegramcampaign",
                        "Может отправлять тест клиентской Telegram-рассылки",
                    ),
                    (
                        "publish_customertelegramcampaign",
                        "Может запускать клиентскую Telegram-рассылку",
                    ),
                ),
                "verbose_name": "Telegram-рассылка",
                "verbose_name_plural": "Telegram-рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="customertelegramcampaignrecipient",
            options={
                "verbose_name": "Получатель Telegram-рассылки",
                "verbose_name_plural": "Получатели Telegram-рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="customertelegramlink",
            options={
                "verbose_name": "Связь Telegram с аккаунтом",
                "verbose_name_plural": "Связи Telegram с аккаунтами",
            },
        ),
        migrations.AlterModelOptions(
            name="customertelegramupdate",
            options={
                "verbose_name": "Обновление от Telegram",
                "verbose_name_plural": "Обновления от Telegram",
            },
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="audience_built_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата формирования аудитории"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="blocked_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Заблокировали бота"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="body_ru",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(3200)],
                verbose_name="Текст сообщения на русском",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="body_uz",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(3200)],
                verbose_name="Текст сообщения на узбекском",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="button_text_ru",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Текст кнопки на русском",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="button_text_uz",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Текст кнопки на узбекском",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="button_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Допускаются только HTTPS-ссылки на сайт BodySteel.",
                max_length=500,
                verbose_name="Ссылка кнопки",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_telegram_campaigns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="delivered_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Доставлено"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="failed_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ошибок доставки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="name",
            field=models.CharField(
                max_length=120, verbose_name="Внутреннее название кампании"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="recipient_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Всего получателей"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Оставьте пустым, чтобы начать отправку сразу после подтверждения.",
                null=True,
                verbose_name="Запланировать отправку на",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала отправки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("scheduled", "Запланирована"),
                    ("queueing", "Формируется очередь"),
                    ("sending", "Отправляется"),
                    ("completed", "Завершена"),
                    ("cancelled", "Отменена"),
                    ("failed", "Ошибка"),
                ],
                db_index=True,
                default="draft",
                max_length=12,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="test_recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_campaigns",
                to="customer_telegram.customertelegramchat",
                verbose_name="Получатель тестового сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="title_ru",
            field=models.CharField(max_length=200, verbose_name="Заголовок на русском"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="title_uz",
            field=models.CharField(
                max_length=200, verbose_name="Заголовок на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество попыток"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="customer_telegram.customertelegramcampaign",
                verbose_name="Кампания",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_deliveries",
                to="customer_telegram.customertelegramchat",
                verbose_name="Telegram-клиент",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата доставки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="failure_code",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Код ошибки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("uz", "O‘zbekcha")],
                max_length=2,
                verbose_name="Язык сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="lease_token",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Токен обработки",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="locked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата блокировки на обработку"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="next_attempt_at",
            field=models.DateTimeField(db_index=True, verbose_name="Следующая попытка"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="rendered_body",
            field=models.TextField(max_length=3200, verbose_name="Отправленный текст"),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="rendered_button_text",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Текст кнопки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="rendered_button_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Ссылка кнопки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="rendered_title",
            field=models.CharField(
                max_length=200, verbose_name="Отправленный заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("sending", "Отправляется"),
                    ("delivered", "Доставлено"),
                    ("retry", "Ожидает повторной попытки"),
                    ("failed", "Ошибка"),
                    ("skipped", "Пропущено"),
                    ("blocked", "Бот заблокирован"),
                ],
                default="pending",
                max_length=12,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="telegram_message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="ID сообщения Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramcampaignrecipient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата блокировки бота"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="chat_id",
            field=models.BigIntegerField(unique=True, verbose_name="ID чата Telegram"),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Бот активен"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("ru", "Русский"), ("uz", "O‘zbekcha")],
                default="",
                max_length=2,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата привязки аккаунта"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="marketing_consent_source",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Источник согласия на рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="marketing_next_send_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Следующую рассылку можно отправить после",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="marketing_opt_in",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Согласен на рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="marketing_opted_in_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата согласия на рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="marketing_opted_out_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отказа от рассылок"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="telegram_user_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="ID пользователя Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="customertelegramchat",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_telegram_chat",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь сайта",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="auth_challenge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_telegram_link",
                to="users.authchallenge",
                verbose_name="Запрос подтверждения аккаунта",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="links",
                to="customer_telegram.customertelegramchat",
                verbose_name="Telegram-клиент",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="consumed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата использования"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="contact_attempts_remaining",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="Осталось попыток отправки контакта"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="expires_at",
            field=models.DateTimeField(db_index=True, verbose_name="Действует до"),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("uz", "O‘zbekcha")],
                max_length=2,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration_otp", "Код регистрации"),
                    ("password_reset_otp", "Код сброса пароля"),
                    ("account_link", "Привязка аккаунта"),
                ],
                max_length=24,
                verbose_name="Назначение",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="registration_challenge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_telegram_link",
                to="users.phoneverificationchallenge",
                verbose_name="Запрос подтверждения регистрации",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="state",
            field=models.CharField(
                choices=[
                    ("awaiting_start", "Ожидает запуска бота"),
                    ("awaiting_contact", "Ожидает отправки контакта"),
                    ("delivering", "Отправляется"),
                    ("delivered", "Доставлен"),
                    ("consumed", "Использован"),
                    ("locked", "Заблокирован"),
                    ("expired", "Истёк"),
                    ("failed", "Ошибка"),
                ],
                default="awaiting_start",
                max_length=20,
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="token_digest",
            field=models.CharField(
                editable=False, max_length=64, unique=True, verbose_name="Хеш токена"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="customertelegramlink",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_telegram_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь сайта",
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramupdate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата получения"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramupdate",
            name="failure_code",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Код ошибки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramupdate",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обработки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramupdate",
            name="status",
            field=models.CharField(
                default="processing", max_length=16, verbose_name="Статус обработки"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramupdate",
            name="update_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="ID обновления Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="customertelegramupdate",
            name="update_type",
            field=models.CharField(max_length=32, verbose_name="Тип обновления"),
        ),
    ]
