# Generated by Django 5.2.17 on 2026-08-26 09:01

import django.db.models.deletion
import store.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_mealproduct"),
        ("store", "0043_alter_basket_created_at_alter_basket_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allergen",
            options={"verbose_name": "Аллерген", "verbose_name_plural": "Аллергены"},
        ),
        migrations.AlterModelOptions(
            name="deliverymethod",
            options={
                "verbose_name": "Способ доставки",
                "verbose_name_plural": "Способы доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="deliveryslot",
            options={
                "ordering": ("delivery_date", "starts_at"),
                "verbose_name": "Интервал доставки",
                "verbose_name_plural": "Интервалы доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="deliveryzone",
            options={
                "verbose_name": "Зона доставки",
                "verbose_name_plural": "Зоны доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="foodtag",
            options={"verbose_name": "Тег блюда", "verbose_name_plural": "Теги блюд"},
        ),
        migrations.AlterModelOptions(
            name="mealkititem",
            options={
                "ordering": ("position", "id"),
                "verbose_name": "Блюдо в наборе",
                "verbose_name_plural": "Блюда в наборе",
            },
        ),
        migrations.AlterModelOptions(
            name="nutritionprofile",
            options={
                "verbose_name": "Профиль питания",
                "verbose_name_plural": "Профили питания",
            },
        ),
        migrations.AlterField(
            model_name="allergen",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="allergen",
            name="name_uz",
            field=models.CharField(
                max_length=100, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="allergen",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Адрес аллергена (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="base_fee",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Базовая стоимость доставки"
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Код способа доставки"),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="free_from",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Бесплатная доставка от суммы"
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="kind",
            field=models.CharField(
                choices=[("courier", "Курьер"), ("pickup", "Самовывоз")],
                default="courier",
                max_length=20,
                verbose_name="Тип доставки",
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="minimum_order",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Минимальная сумма заказа"
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="name_uz",
            field=models.CharField(
                max_length=100, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="capacity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Вместимость интервала"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="cutoff_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Принимать заказы до"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="delivery_date",
            field=models.DateField(verbose_name="Дата доставки"),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="ends_at",
            field=models.TimeField(verbose_name="Время окончания интервала"),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="reserved_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Зарезервировано мест"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="starts_at",
            field=models.TimeField(verbose_name="Время начала интервала"),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="nutrition.deliveryzone",
                verbose_name="Зона доставки",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="code",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="Код зоны"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="fee",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Стоимость доставки"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="name_ru",
            field=models.CharField(max_length=150, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="name_uz",
            field=models.CharField(
                max_length=150, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="foodtag",
            name="name_ru",
            field=models.CharField(max_length=100, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="foodtag",
            name="name_uz",
            field=models.CharField(
                max_length=100, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="foodtag",
            name="slug",
            field=models.SlugField(
                max_length=80, unique=True, verbose_name="Адрес тега (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="mealkititem",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="included_in_kits",
                to="store.product",
                verbose_name="Блюдо в наборе",
            ),
        ),
        migrations.AlterField(
            model_name="mealkititem",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit_items",
                to="store.product",
                verbose_name="Набор",
            ),
        ),
        migrations.AlterField(
            model_name="mealkititem",
            name="position",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="mealkititem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="allergens",
            field=models.ManyToManyField(
                blank=True,
                related_name="nutrition_profiles",
                to="nutrition.allergen",
                verbose_name="Аллергены",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="allowed_delivery_methods",
            field=models.ManyToManyField(
                blank=True,
                related_name="nutrition_profiles",
                to="nutrition.deliverymethod",
                verbose_name="Разрешённые способы доставки",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="calories_kcal",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Калорийность, ккал"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="carbohydrate_grams",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=7, verbose_name="Углеводы, г"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="fat_grams",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=7, verbose_name="Жиры, г"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Доступен для заказа"),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="kind",
            field=models.CharField(
                choices=[("dish", "Блюдо"), ("meal_kit", "Набор")],
                default="dish",
                max_length=20,
                verbose_name="Тип питания",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="portion_weight_grams",
            field=models.PositiveIntegerField(default=0, verbose_name="Вес порции, г"),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_profile",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="protein_grams",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=7, verbose_name="Белки, г"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="requires_cooling",
            field=models.BooleanField(default=False, verbose_name="Требует охлаждения"),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="serving_ru",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Рекомендации по подаче на русском"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="serving_uz",
            field=store.fields.SanitizedHtmlField(
                blank=True,
                default="",
                verbose_name="Рекомендации по подаче на узбекском",
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="servings",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество порций"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="shelf_life_hours",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Срок хранения, часов"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="storage_ru",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Условия хранения на русском"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="storage_uz",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Условия хранения на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionprofile",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="nutrition_profiles",
                to="nutrition.foodtag",
                verbose_name="Теги блюда",
            ),
        ),
    ]
