# Generated by Django 5.2.17 on 2026-08-26 09:01

import courses.models
import django.core.validators
import django.db.models.deletion
import store.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_lesson_video_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ("sort_order", "-created_at"),
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="courseaccess",
            options={
                "verbose_name": "Доступ к курсу",
                "verbose_name_plural": "Доступы к курсам",
            },
        ),
        migrations.AlterModelOptions(
            name="coursemodule",
            options={
                "ordering": ("position", "id"),
                "verbose_name": "Модуль курса",
                "verbose_name_plural": "Модули курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="coursepurchase",
            options={
                "verbose_name": "Покупка курса",
                "verbose_name_plural": "Покупки курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("position", "id"),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonmaterial",
            options={
                "ordering": ("position", "id"),
                "verbose_name": "Материал урока",
                "verbose_name_plural": "Материалы уроков",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonprogress",
            options={
                "verbose_name": "Прогресс урока",
                "verbose_name_plural": "Прогресс уроков",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="access_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Оставьте пустым, чтобы доступ не был ограничен по времени.",
                null=True,
                verbose_name="Срок доступа после покупки, дней",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=courses.models.course_cover_path,
                verbose_name="Обложка курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="course",
            name="currency",
            field=models.CharField(default="UZS", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description_ru",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Полное описание на русском"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description_uz",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Полное описание на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Продолжительность курса, дней"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Расчётная длительность, минут"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="sales_end_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Окончание продаж"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="sales_start_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало продаж"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                help_text="Уникальная часть ссылки латиницей, например: pravilnoe-pitanie.",
                max_length=255,
                unique=True,
                verbose_name="Адрес курса (URL)",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("published", "Опубликован"),
                    ("archived", "Архив"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_ru",
            field=models.TextField(
                max_length=2000, verbose_name="Краткое описание на русском"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary_uz",
            field=models.TextField(
                max_length=2000, verbose_name="Краткое описание на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_ru",
            field=models.CharField(max_length=255, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title_uz",
            field=models.CharField(
                max_length=255, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_grants",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Доступ действует до"
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="granted_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата выдачи доступа"
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_grants",
                to="courses.coursepurchase",
                verbose_name="Покупка курса",
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="revoke_reason",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Причина отзыва"
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отзыва доступа"
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="source",
            field=models.CharField(
                choices=[("purchase", "Покупка"), ("manual", "Выдан вручную")],
                default="purchase",
                max_length=20,
                verbose_name="Источник доступа",
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("revoked", "Отозван"),
                    ("expired", "Истёк"),
                ],
                db_index=True,
                default="active",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="courseaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_accesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="description_ru",
            field=models.TextField(
                blank=True,
                default="",
                max_length=2000,
                verbose_name="Описание на русском",
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="description_uz",
            field=models.TextField(
                blank=True,
                default="",
                max_length=2000,
                verbose_name="Описание на узбекском",
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="position",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="title_ru",
            field=models.CharField(max_length=255, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="title_uz",
            field=models.CharField(
                max_length=255, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="coursemodule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="amount",
            field=models.PositiveBigIntegerField(verbose_name="Сумма"),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="course_title",
            field=models.CharField(
                max_length=255, verbose_name="Название курса на момент покупки"
            ),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="currency",
            field=models.CharField(default="UZS", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="idempotency_digest",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Ключ защиты от дублирования"
            ),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="request_fingerprint",
            field=models.CharField(
                default="", max_length=64, verbose_name="Отпечаток запроса"
            ),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("payment_pending", "Ожидает оплаты"),
                    ("paid", "Оплачена"),
                    ("cancelled", "Отменена"),
                    ("refunded", "Возвращена"),
                ],
                db_index=True,
                default="created",
                max_length=24,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="coursepurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Продолжительность, минут"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=courses.models.lesson_image_path,
                verbose_name="Изображение урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(
                default=False, verbose_name="Доступен для предпросмотра"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.coursemodule",
                verbose_name="Модуль курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="position",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="text_ru",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Текст урока на русском"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="text_uz",
            field=store.fields.SanitizedHtmlField(
                blank=True, default="", verbose_name="Текст урока на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title_ru",
            field=models.CharField(max_length=255, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title_uz",
            field=models.CharField(
                max_length=255, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="external_url",
            field=models.URLField(
                blank=True, default="", max_length=1000, verbose_name="Внешняя ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=courses.models.lesson_material_path,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="is_downloadable",
            field=models.BooleanField(
                default=True, verbose_name="Разрешить скачивание"
            ),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="kind",
            field=models.CharField(
                choices=[
                    ("file", "Файл"),
                    ("image", "Изображение"),
                    ("video", "Видео"),
                    ("audio", "Аудио"),
                ],
                default="file",
                max_length=40,
                verbose_name="Тип материала",
            ),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="courses.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="position",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="title_ru",
            field=models.CharField(max_length=255, verbose_name="Название на русском"),
        ),
        migrations.AlterField(
            model_name="lessonmaterial",
            name="title_uz",
            field=models.CharField(
                max_length=255, verbose_name="Название на узбекском"
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="access",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="courses.courseaccess",
                verbose_name="Доступ к курсу",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="courses.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="percent",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Пройдено, %"
            ),
        ),
        migrations.AlterField(
            model_name="lessonprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
