import os


_DEBUG_ENABLED = os.getenv('DEBUG', '').strip().lower() in {'1', 'true', 'yes'}
_PREVIOUS_SECRET_KEY = os.getenv('SECRET_KEY_PREVIOUS', '')

SECRET_KEY_FALLBACKS = (_PREVIOUS_SECRET_KEY,) if _PREVIOUS_SECRET_KEY else ()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not _DEBUG_ENABLED
SESSION_COOKIE_SECURE = not _DEBUG_ENABLED
CSRF_COOKIE_SECURE = not _DEBUG_ENABLED
SECURE_HSTS_SECONDS = 0 if _DEBUG_ENABLED else 31_536_000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not _DEBUG_ENABLED
SECURE_HSTS_PRELOAD = not _DEBUG_ENABLED
